@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="" id="item-{{ $i }}">
    <td class="padding-10 center" style="width:30px;" nowrap>{{ $i++ }}</td>
	<td class="padding-10" nowrap>{{ $item->name }}</td>
	<td class="padding-10" nowrap>{{ $item->tiername	 }}</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="3" class="padding-10 center">
        <br>
		@include('admin.body.actionmessage')
    </td>
</tr>
@else
<tr>
<td colspan="3" class="padding-10 center">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('deptvendors.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

