@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
    <td nowrap>{{ __($item->mastermenu) }}</td>
	<td nowrap>{{ $item->permission_name }}</td>
	<td nowrap>{{ $item->route_name }}</td>
	<td nowrap>{{ $item->display_order }}</td>
	<td nowrap>{{ $item->permission_type }}</td>
    <td nowrap style="text-align:center;"><a href="{{ route('edit.actionpermission',$item->permissionid) }}" title=""><i class="fa fa-edit"></i></a></td>
    <td nowrap style="text-align:center;">
        <a title="" onclick="deleteItem('actionpermission',{{ $item->permissionid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','MENU DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="8" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        SORRY!<br>
        THE SYSTEM DID NOT FIND THE DATA YOU ARE LOOKING FOR.
    </td>
</tr>
@else
<tr>
<td colspan="8" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('actionpermission.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

