@extends('admin.admin_master')
@section('admin')
@php
$t=0;
@endphp

<div class="main-content">
	<div class="main-content-inner">
			<div class="page-content" style="padding:10px 15px!important;">
				<div class="ace-settings-container" id="ace-settings-container"></div>
				<div class="row">
					<div class="col-xs-12">
					<!-- PAGE CONTENT BEGINS -->
<div class="tabbable" style="padding:0px 0px!important;">
		<ul class="nav nav-tabs padding-0">
			<li class="active">
				<a data-toggle="tab" href="#home">
					<i class="green ace-icon fa fa-list-alt bigger-120 datalist" style="vertical-align:bottom;"></i> EoI's
				</a>
			</li>
		</ul>

		<div class="tab-content no-border" style="min-height:100px; border-radius:0px!important;">
<div id="home" class="tab-pane in active">
		<form name="eoi_data" id="eoi_data" action="#" method="post" onsubmit="return false;">
				@if(Session::has('success'))
				
				<div class="col-sm-12 mt-10">
					<div class="alert alert-block alert-success">
				    	<button type="button" class="close" data-dismiss="alert">
							<i class="ace-icon fa fa-times"></i>
						</button>
						{{ Session::get('success') }}
					</div>
				</div>
				
				@endif
				<div class="table-responsive">
				<table class="table-bordered pd-8 mytable">
				
				<tr>
					<td colspan="6">
						<select name="page_size" id="page_size" class="select2" data-width="95">
							<option value="100">100</option>
							<option value="200">200</option>
							<option value="300">300</option>
							<option value="500">500</option>														
						</select>
						<select class="select2" name="project_id" id="project_id" data-width="200"	data-placeholder="Project Name">
							<option value=""></option>
							@foreach ($projects as $project)
							<option value="{{ $project->projectid }}">{{ $project->project_name }}</option>
							@endforeach
						</select>
						
						<select class="select2" name="department_id" id="department_id" data-width="200"	data-placeholder="Departments">
							<option value=""></option>
							@foreach ($departments as $itm)
								<option value="{{ $itm->userid }}">
									{{ strtoupper($itm->shortname) }}-{{ $itm->departmentname }}
								</option>
							@endforeach
						</select>
						
						<span class="input-icon" style="width:250px!important; height:38px!important; line-height:38px!important;">
							<input type="text" placeholder="Search ..." class="" id="pagesearch" name="pagesearch" autocomplete="off" tabindex="<?php echo $t++;?>" style="width:250px!important; border-radius:5px; height:38px!important; line-height:38px!important;" />
							<i class="ace-icon fa fa-search nav-search-icon padding-0"></i>
						</span>
						<button type="submit" class="btn btn-info gridbtn width-100" onclick="loadData(1,'{{ route('finance.department.availablefund') }}')" tabindex="{{$t++}}"><i class="fa fa-search"></i> Search</button>
					</td>
				</tr>
				<tr class="bg-primary">
					<td>EOI Number</td>
					<td>Fund Type</td>
					<td class="text-right no_wrap">Opening Balance (₹)</td>
					<td class="text-right no_wrap">Received (₹)</td>
					<td class="text-right no_wrap">Utilized (₹)</td>
					<td class="text-right no_wrap">Available Balance (₹)</td>
				</tr>
				
				<tbody class="tabledata">
				<tr><td class="center" colspan="6">--EoI List--</td></tr>
				</tbody>
				</table>
				</div>
		</form>
</div>

</div>
</div>


						
				</div><!-- /.col -->
			</div><!-- /.row -->
		</div><!-- /.page-content -->
	
		
	</div>
</div>
<script src="{{ asset('panel/assets/js/jquery-2.1.4.min.js') }}"></script>
<script>

function loadData(page, r1)
{
	var pagesize 	= document.getElementById("page_size").value;
	var projectid 	= document.getElementById("project_id").value;
	var departmentid= document.getElementById("department_id").value;
	var pagesearch 	= document.getElementById("pagesearch").value;
	
	$.get("" + r1,
		{
			page: page,
			pagesize: pagesize,
			pagesearch: pagesearch,
			departmentid: departmentid,
			projectid:projectid
		},
		function (data, status) {
			$(".tabledata").html(data);
			const paginationLinks = document.querySelectorAll('.pagination a');
			paginationLinks.forEach(link => {
				link.onclick = function (event) {
					event.preventDefault(); // Prevent default link behavior
					const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
					const url = '{{ route('finance.demandnote.eoilist') }}'; // URL generated by Laravel route
					loadData(page, url); // Call custom function with page number and URL
				};
			});	
			
		});
}

</script>

<script src="{{ asset('panel/assets/js/datatablePaginationWithFilter.js') }}"></script>
@endsection