@foreach($data as $order)
<tr class="bg-primary font-bold">
	<td colspan="9" style="position:relative;">
		{{$loop->iteration}}) {{$order->ordernumber}} | Order Date : {{date('d\-m\-Y',strtotime($order->orderdate))}} | Order Due Date : {{date('d\-m\-Y',strtotime($order->workorderduedate))}}
		
		<button type="button" class="btn-warning gridbtn width-100" style="position:absolute; right:5px; top:5px;" onclick="loadPendingInvoices('{{route('pending.invoices')}}','{{Crypt::encrypt($order->orderid)}}')">Generate Invoice</button>
	</td>
</tr>
<tr class="myheadbg font-bold">
	<td>S. No.</td>
	<td>MPR Number</td>
	<td class="text-center">Submission Date</td>
	<td class="text-center">MPR Month</td>
	<td class="text-right">Submitted Amount</td>
	<td class="text-right">Approved Amount</td>
	<td class="text-center">MPR File</td>
	<td class="text-center">Attendance File</td>
	<td class="text-center">Supporting File</td>
</tr>
@php
$total_submitted=	0;
$total_approved	=	0;
@endphp
@foreach($order->mprs as $mpr)
<tr>
	<td class="text-center">{{$loop->iteration}}</td>
	<td>{{$mpr->mpr_number}}</td>
	<td class="text-center">{{date('d\-m\-Y',strtotime($mpr->submission_date))}}</td>
	<td class="text-center">{{ date('F', mktime(0, 0, 0, $mpr->mpr_month, 1)) }}-{{ $mpr->mpr_year }}</td>
	<td class="text-right format-indian" data-value="{{$mpr->mpr_value}}"></td>
	<td class="text-right format-indian" data-value="{{$mpr->mpr_approved_value}}"></td>
	<td class="text-center">
		@if($mpr->signed_mpr)
		<a href="{{route('view.uploadedfile',Crypt::encrypt($mpr->signed_mpr))}}" target="_blank">
			<i class="fa fa-file-pdf-o"></i>
		</a>
		@else
			<i class="fa fa-remove"></i>
		@endif
	</td>
	<td class="text-center">
		@if($mpr->signed_attendance)
		<a href="{{route('view.uploadedfile',Crypt::encrypt($mpr->signed_attendance))}}" target="_blank">
			<i class="fa fa-file-pdf-o"></i>
		</a>
		@else
			<i class="fa fa-remove"></i>
		@endif
	</td>
	<td class="text-center">
		@if($mpr->signed_supporting)
		<a href="{{route('view.uploadedfile',Crypt::encrypt($mpr->signed_supporting))}}" target="_blank">
			<i class="fa fa-file-pdf-o"></i>
		</a>
		@else 
			<i class="fa fa-remove"></i>
		@endif
	</td>
</tr>
@php
$total_submitted	=	$total_submitted+$mpr->mpr_value;
$total_approved		=	$total_approved+$mpr->mpr_approved_value;
@endphp
@endforeach
<tr class="myheadbg font-bold">
	<td colspan="4" class="text-right">Grand Total</td>
	<td class="text-right format-indian font-14" data-value="{{number_format($total_submitted,'2','.','')}}"></td>
	<td class="text-right format-indian font-14" data-value="{{number_format($total_approved,'2','.','')}}"></td>
	<td colspan="3"></td>
</tr>
@endforeach

@if($data->count()==0)
<tr>
    <td colspan="9" class="padding-10" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="9" class="padding-10" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
document.querySelectorAll('.format-indian').forEach(function(el) {
	el.style.fontWeight = 'bold';
    el.innerText = formatIndianNumber(el.dataset.value);
});

const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('vendor.approved.mprs.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });

</script>