@php
$i=1;
$amount=0;
$tax=0;
$invoice=0;
@endphp
@foreach ($data as $item)
<tr class="" id="">
    <td style="width:30px; text-align:center;" nowrap>{{ $loop->iteration }}</td>
<td style="text-align:left; width:400px;">
    <div style="display:flex; flex-direction:column; gap:0px;">
        <div>{{ $item->project_name }}</div>
        @if($item->mpr_file!='')
        <a href="{{route('view.uploadedfile',Crypt::encrypt($item->mpr_file))}}" target="_blank" class="action-a" style="width:150px;">
            <span class="label label-white middle f-s-10 form-label span-content" style="width:100%; text-align:left;">
                <i class="fa fa-file-pdf-o"></i> Combined MPR File
            </span>
        </a>
        @endif

        @if($item->attendance_file!='')
        <a href="{{route('view.uploadedfile',Crypt::encrypt($item->attendance_file))}}" target="_blank" class="action-a" style="width:150px;">
            <span class="label label-white middle f-s-10 form-label span-content" style="width:100%; text-align:left;">
                <i class="fa fa-file-pdf-o"></i> Combined Attendance File
            </span>
        </a>
        @endif

        @if($item->supporting_file!='')
        <a href="{{route('view.uploadedfile',Crypt::encrypt($item->supporting_file))}}" target="_blank" class="action-a" style="width:150px;">
            <span class="label label-white middle f-s-10 form-label span-content" style="width:100%; text-align:left;">
                <i class="fa fa-file-pdf-o"></i> Supporting Document
            </span>
        </a>
        @endif

        @if($item->invoice_file!='')
        <a href="{{route('view.uploadedfile',Crypt::encrypt($item->invoice_file))}}" target="_blank" class="action-a" style="width:150px;">
            <span class="label label-white middle f-s-10 form-label span-content" style="width:100%; text-align:left;">
                <i class="fa fa-file-pdf-o"></i> Invoice File
            </span>
        </a>
        @endif

    </div>
</td>
	<td class="center" nowrap style="padding:2px!important; vertical-align:top!important;">
		<table style="width:100%!important;">
			<tr>
				<td style="padding:5px!important; text-align:left;">Submit Date</td>
				<td style="padding:5px!important; text-align:left;">{{date('d\-m\-Y',strtotime($item->request_date))}}</td>
			</tr>
			<tr>
				<td nowrap style="padding:5px!important; text-align:left;">Invoice Date</td>
				<td style="padding:5px!important; text-align:left;">{{date('d\-m\-Y',strtotime($item->invoice_date))}}</td>
			</tr>
			<tr>
				<td style="padding:5px!important; text-align:left;">Invoice Number</td>
				<td style="padding:5px!important; text-align:left;">{{ $item->invoice_number }}</td>
			</tr>
			<tr>
				<td style="padding:5px!important; text-align:left;">Month</td>
				<td style="padding:5px!important; text-align:left;">{{ date('M-Y', strtotime($item->mpr_year . '-' . $item->mpr_month . '-01')) }}</td>
			</tr>
			@if($item->name)
			<tr>
				<td style="padding:5px!important; text-align:left;">Created By</td>
				<td style="padding:5px!important; text-align:left;">{{$item->name}}</td>
			</tr>
			@endif
		</table>
	</td>
	<td class="center" style="padding:2px!important; vertical-align:top!important;">
		<table style="width:100%!important;">
			<tr>
				<td nowrap style="padding:5px!important; text-align:left;">Taxable Amount</td>
				<td nowrap style="padding:5px!important; text-align:left;" class="format-indian" data-value="{{ $item->amount_value }}"></td>
			</tr>
			<tr>
				<td style="padding:5px!important; text-align:left;">Tax Value</td>
				<td style="padding:5px!important; text-align:left;" class="format-indian" data-value="{{ $item->tax_value }}"></td>
			</tr>
			<tr>
				<td style="padding:5px!important; text-align:left;">Invoice Value</td>
				<td style="padding:5px!important; text-align:left;" class="format-indian" data-value="{{ $item->invoice_value }}"></td>
			</tr>
		
		</table>
	</td>

</tr>
@endforeach
@if($data->count()==0)
<tr>
    <td colspan="4" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="4" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('invoicehistory.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });

document.querySelectorAll('.format-indian').forEach(function(el) {
    el.innerText = formatIndianNumber(el.dataset.value);
});
		
</script>

