@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td nowrap>{{ $item->eoinumber }}<br>
	@if($item->eoi_file!='')
	<a href="{{ route('view.uploadedfile',Crypt::encrypt($item->eoi_file))}}" target="_blank" class="action-a">
	<span class="label label-white middle animated flipInX f-s-10 form-label">
		<i class="ace-icon fa fa-download bigger-120"></i> Download EoI
	</span>
	</a>
	@endif
	
	@if($item->presentationfile=='' && $item->isresumeuploaded==0)
	<a href="{{ route('fillform.view',Crypt::encrypt($item->floatid))}}" class="action-a">
	<span class="label label-white middle animated flipInX f-s-10 form-label">
		<i class="ace-icon fa fa-hand-o-right bigger-120 icon-animated-bell"></i> Upload Resume
	</span>	
	</a>
	@else
		@if($item->isenabled==1)
		<a href="{{ route('fillform.view',Crypt::encrypt($item->floatid))}}">
			<span class="label label-success middle animated flipInX f-s-10 form-label action-a span-content">
				<i class="ace-icon fa fa-hand-o-right bigger-120 icon-animated-bell"></i> View Resumes / PPT Uploaded
			</span>	
		
		</a>
		@else
		<span class="btn btn-success no-hover" style="width:100%;">Order Created</span>
		<span class="label label-success middle animated flipInX f-s-10 form-label action-a span-content">
			<i class="fa fa-th-list"></i> Order Created
		</span>	
	
		@endif
	@endif
	
	</td>
	<td style="width:300px;">{{ $item->projecttitle }}</td>
	<td>
		<table class="pd-5" style="width:100%;">
			<tr>
				<td>Release Date of EoI by CHiPS</td>
				<td>: 
				@if($item->eoistatus>=2)
					@if(!empty($item->releasedate)) {{ date('d\-m\-Y',strtotime($item->releasedate)) }} @endif
				@endif
				</td>
			</tr>
			<tr>
				<td>Last Date of Pre-bid Query</td>
				<td>: 
					@if($item->prebidlastdate!='' && $item->prebidlastdate!='0000-00-00') {{ date('d\-m\-Y',strtotime($item->prebidlastdate)) }} @endif
				</td>
			</tr>
			<tr>
				<td>Last Date for Submission of Proposals</td>
				<td nowrap>: @if($item->deadlinedate!='' && $item->deadlinedate!='0000-00-00') {{ date('d\-m\-Y h:i A',strtotime($item->deadlinedate)) }} @endif</td>
			</tr>
			<tr>
				<td nowrap>Tentative Date of Presentation and Interview</td>
				<td nowrap>: @if($item->interviewdate!='' && $item->interviewdate!='0000-00-00') {{ date('d\-m\-Y',strtotime($item->interviewdate)) }} @endif</td>
			</tr>
		</table>
	</td>

</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="4" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="4">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('participatedeoi.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

