@foreach($data as $order)
<tr>
	<td class="text-center">{{$loop->iteration}}</td>
	<td class="width-400 lh-25">
		{{$order->eoinumber}}<br>
		Order Date : {{date('d\-m\-Y',strtotime($order->orderdate))}} | Due Date : {{date('d\-m\-Y',strtotime($order->workorderduedate))}}
		<br><b>{{$order->ordernumber}}</b>
		<br>{{$order->name}}
		<br><span class="width-300">{{$order->project_name}}</span>
	</td>
	<td>
	@foreach($order->months as $month)
<span class="label label-white middle animated flipInX delay-9 f-s-20 form-label span-content" style="width:100px!important; height:90px; margin-right:20px!important; margin:0 auto; margin-bottom:15px; border-radius:15px 15px 15px 15px; cursor:pointer;" onclick="loadResources('{{route('mpr.resources')}}','{{Crypt::encrypt($order->orderid)}}',{{$month['mprid']}},{{$month['month']}},{{$month['year']}})">
	<i class="fa fa-calendar"></i>
	<div class="year">{{$month['year']}}</div>
	<div class="month">{{$month['month_name']}}</div>
	<div class="year">{{$month['label']}}</div>
</span>
	
	@endforeach
	</td>
</tr>
@endforeach

@if($data->count()==0)
<tr>
    <td colspan="3" class="padding-10" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="3" class="padding-10" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif
<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('vendor.pending.mprs.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>
