@php
$i = 1;
@endphp
@foreach ($data as $item)
	<tr class="mytr pd-8" id="item-{{ $i }}">
		<td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
		<td nowrap>{{ $item->name}}</td>
		<td nowrap>{{ $item->mobilenumber}}</td>
		<td nowrap>{{ strtolower($item->email)}}</td>
		<td nowrap class="center">
			<a href="{{ route('edit.vendoruser', Crypt::encrypt($item->userid)) }}" class="btn myfrmbtn smbtn"> Edit</a>
		</td>
	</tr>
@endforeach
@if($i == 1)
	<tr>
		<td colspan="5" style="text-align:center;">
			<br>
			@include('admin.body.actionmessage')
		</td>
	</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('admininvoicehistory.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});

</script>