@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td nowrap>{{ $item->actionname }}</td>
	<td nowrap style="text-align:center; width:120px;">{{ $item->displayorder }}</td>
    <td nowrap style="text-align:center;"><a href="{{ route('edit.action',$item->actionid) }}" title=""><i class="fa fa-edit"></i></a></td>
    <td nowrap style="text-align:center;">
        <a title="" onclick="deleteItem('action',{{ $item->actionid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','ACTION DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="5" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="5" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('action.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

