@php
$i=1
@endphp
@foreach ($data as $item)
<tr id="item-{{ $i }}" class="mytr">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td nowrap style="text-align:left;">{{ $item->category }}</td>
	<td nowrap style="text-align:left;">{{ $item->servicetitle }}</td>
	<td nowrap style="text-align:left;">
		MRP : {{ $item->mrp }} INR<br>
		DISCOUNT : {{ $item->discount }}%<br>
		TAXABLE : {{ $item->taxable }} INR<br>
		IGST(%) : {{ $item->igst }}%<br>
		CGST(%) : {{ $item->cgst }}%<br>
		SGST(%) : {{ $item->sgst }}%<br>
		FINAL PRICE : {{ $item->finalprice }} INR<br>
	</td>
	<td nowrap style="text-align:center;">{{ $item->requiredtime }} MIN</td>
	<td nowrap style="text-align:left;">{!! $item->description !!}</td>
	<td nowrap style="text-align:left;">{!! $item->needs !!}</td>
	<td nowrap style="text-align:left;">{!! $item->services !!}</td>
	<td nowrap style="text-align:left;">{{ $item->createdbyname }}</td>
	<td nowrap style="text-align:left;">
	@php
	if($item->isactive==1)
	echo 'ACTIVE';
	else
	echo 'IN ACTIVE';
	@endphp
	</td>	
    <td style="text-align:center; padding:0px; width:100px;">
		@if($item->firstpic!='')
        <img src="{{ asset('storage/'.$item->firstpic) }}" alt="Uploaded Image" style="width:100px; position:relative;">
		@else
		<img src="{{ asset('storage/uploads/images/default.jpg') }}" alt="Uploaded Image" style="width:100px; position:relative;">
		@endif
    </td>
    <td style="text-align:center; padding:0px; width:100px;">
		@if($item->secondpic!='')
        <img src="{{ asset('storage/'.$item->secondpic) }}" alt="Uploaded Image" style="width:100px; position:relative;">
		@else
		<img src="{{ asset('storage/uploads/images/default.jpg') }}" alt="Uploaded Image" style="width:100px; position:relative;">
		@endif
    </td>
    <td style="text-align:center; padding:0px; width:100px;">
		@if($item->thirdpic!='')
        <img src="{{ asset('storage/'.$item->thirdpic) }}" alt="Uploaded Image" style="width:100px; position:relative;">
		@else
		<img src="{{ asset('storage/uploads/images/default.jpg') }}" alt="Uploaded Image" style="width:100px; position:relative;">
		@endif
    </td>
    <td style="text-align:center; padding:0px; width:100px;">
		@if($item->fourthpic!='')
        <img src="{{ asset('storage/'.$item->fourthpic) }}" alt="Uploaded Image" style="width:100px; position:relative;">
		@else
		<img src="{{ asset('storage/uploads/images/default.jpg') }}" alt="Uploaded Image" style="width:100px; position:relative;">
		@endif
    </td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.service',$item->serviceid) }}" title="" class="myactionlink"><i class="fa fa-edit"></i></a></td>
	@endif
    <td nowrap style="text-align:center;">
    @if(in_array(3,Session::get('actions')))
		<a title="" class="myactionlink" onclick="deleteItem('service',{{ $item->serviceid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','SERVICE DETAIL DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="16" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        SORRY!<br>
        THE SYSTEM DID NOT FIND THE DATA YOU ARE LOOKING FOR.
    </td>
</tr>
@else
<tr>
<td colspan="16" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('service.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

