@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="myheadbg">
	<td colspan="2">{{ $i }}) {{ $item->name }} | GENDER : {{ $item->gender }} | MOBILE : {{ $item->mobilenumber }} | EMAIL : {{ $item->email }} | USER NAME : {{ $item->username }} | PASSWORD : {{ $item->password }}
	
	<span style="float:right; margin-right:10px;">
	@if(in_array(3,Session::get('actions')))
		@if($item->issuper!=1)
        <a title="" class="myactionlink" onclick="deleteItem('appuser',{{ $item->userid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','USER DETAIL DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash" style="color:white!important;"></i>
        </a>
		@endif
	@endif	
	</span>
	<span style="float:right; margin-right:15px;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.appuser',$item->userid) }}" title="" class="myactionlink"><i class="fa fa-edit" style="color:white!important;"></i></a>
	@endif	
	</span>
	</td>
</tr>
<tr>
	<td style="width:150px; text-align:center;">
	@if($item->profilepic!='')
        <a href="{{ asset('storage/'.$item->profilepic) }}" target="_blank">
			<img src="{{ asset('storage/'.$item->profilepic) }}" alt="Uploaded Image" style="width:150px; position:relative;">
		</a>
	@else
		<img src="{{ asset('storage/uploads/images/avatar.png') }}" alt="Uploaded Image" style="width:150px; position:relative;">
	@endif
	</td>
	<td style="padding:2px;">
		<table class="mytable" border="1">
			<tr>
				<td class="mybgtd">FATHER NAME</td>
				<td>{{$item->fathername}}</td>
				<td class="mybgtd">DATE OF BIRTH</td>
				<td>@if($item->dob!='') {{date('d\-m\-Y',strtotime($item->dob))}} @endif</td>
				<td></td>
			</tr>
			<tr>
				<td class="mybgtd">DEPARTMENT NAME</td>
				<td>{{$item->departmentname}}</td>
				<td class="mybgtd">DESIGNATION NAME</td>
				<td>{{$item->designationname}}</td>
				<td></td>
			</tr>
			<tr>
				<td class="mybgtd">CHECK IN TIME</td>
				<td>{{date('h:i A',strtotime($item->checkintime))}}</td>
				<td class="mybgtd">CHECK OUT TIME</td>
				<td>{{date('h:i A',strtotime($item->checkouttime))}}</td>
				<td></td>
			</tr>
			<tr>
				<td class="mybgtd">BASIC SALRY</td>
				<td class="mybgtd">TRAVEL ALLOWANCE</td>
				<td class="mybgtd">DEARNESS ALLOWANCE</td>
				<td class="mybgtd">HOUSE RENT ALLOWANCE</td>
				<td class="mybgtd">MEDICAL ALLOWANCE</td>
			</tr>
			<tr>
				<td>{{$item->basicsalary}} INR</td>
				<td>{{$item->ta}} INR</td>
				<td>{{$item->da}} INR</td>
				<td>{{$item->hra}} INR</td>
				<td>{{$item->ma}} INR</td>
			</tr>
			<tr>
				<td class="mybgtd">STATE</td>
				<td class="mybgtd">CITY</td>
				<td class="mybgtd">AREA</td>
				<td class="mybgtd">PIN CODE</td>
				<td class="mybgtd"></td>
			</tr>
			<tr>
				<td>{{$item->statename}}</td>
				<td>{{$item->cityname}}</td>
				<td>{{$item->areaname}}</td>
				<td>{{$item->pincode}}</td>
				<td></td>
			</tr>
			<tr>
				<td class="mybgtd">ADDRESS</td>
				<td colspan="4">{{$item->address}}</td>
			</tr>
			<tr>
				<td class="mybgtd">BANK NAME</td>
				<td class="mybgtd">ACCOUNT NUMBER</td>
				<td class="mybgtd">IFSC CODE</td>
				<td class="mybgtd">BRANCH NAME</td>
				<td class="mybgtd"></td>
			</tr>
			<tr>
				<td>{{$item->bankname}}</td>
				<td>{{$item->accountnumber}}</td>
				<td>{{$item->ifsccode}}</td>
				<td>{{$item->branchname}}</td>
				<td>&nbsp;</td>
			</tr>
		</table>
	</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="2" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        SORRY!<br>
        THE SYSTEM DID NOT FIND THE DATA YOU ARE LOOKING FOR.
    </td>
</tr>
@else
<tr>
<td colspan="2" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('appuser.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

