@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td nowrap style="text-align:left;">{{ $item->name }}</td>
	<td nowrap style="text-align:center;">{{ date('d\-m\-Y',strtotime($item->attendancedate)) }}</td>
	<td nowrap style="text-align:center;">{{ $item->actualcheckin }}</td>
	<td nowrap style="text-align:center;">{{ date('h:i A',strtotime($item->timein)) }}</td>
	<td nowrap style="text-align:center; color:white; @if($item->indiff==0 || $item->indiff>0) background-color:green; @else background-color:red; @endif">
	@if($item->indiff>0)
	{{ abs($item->indiff) }} MIN. EARLY
	@elseif($item->indiff<0)
	{{ abs($item->indiff) }} MIN. LATE
	@else
	{{ 'ACCURATE' }}
	@endif
	</td>
	<td nowrap style="text-align:center;">{{ $item->actualcheckout }}</td>
	<td nowrap style="text-align:center;">@if($item->timeout!='00:00:00') {{ date('h:i A',strtotime($item->timeout)) }} @endif</td>
	<td nowrap style="text-align:center; color:white; @if($item->timeout!='00:00:00') @if($item->outdiff==0 || $item->outdiff<0) background-color:green; @else background-color:red; @endif @endif">
	@if($item->timeout!='00:00:00')
		@if($item->outdiff>0)
		{{ abs($item->outdiff) }} MIN. EARLY
		@elseif($item->outdiff<0)
		{{ abs($item->outdiff) }} MIN. LATE
		@else
		{{ 'ACCURATE' }}
		@endif
	@endif
	</td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.attendance',$item->recordid) }}" title="" class="myactionlink"><i class="fa fa-edit"></i></a>
	@endif
	</td>
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
		
        <a title="" class="myactionlink" onclick="deleteItem('attendance',{{ $item->recordid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','ATTENDANCE RECORD DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
		
	@endif
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="11" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        SORRY!<br>
        THE SYSTEM DID NOT FIND THE DATA YOU ARE LOOKING FOR.
    </td>
</tr>
@else
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('attendance.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

