@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
    <td nowrap>{{ ucwords(strtolower($item->parent_name)) }} @if($item->parent_middlename!=''){{ ucwords(strtolower($item->parent_middlename)) }}@endif @if($item->parent_lastname!=''){{ ucwords(strtolower($item->parent_lastname)) }}@endif</td>

    <td nowrap>{{ ucwords(strtolower($item->name)) }} @if($item->middlename!=''){{ ucwords(strtolower($item->middlename)) }}@endif @if($item->lastname!=''){{ ucwords(strtolower($item->lastname)) }}@endif</td>
    <td nowrap>{{ $item->mobilenumber }}</td>
	<td nowrap>{{ $item->securitydeposit }}</td>
	<td nowrap>{{ $item->walletamount }}</td>
	<td nowrap>@if($item->isavailable==1) AVAILABLE @else NOT AVAILABLE @endif</td>
	<td nowrap>@if($item->isassigned==1) ASSIGNED @else NOT ASSIGNED @endif</td>
	<td nowrap>{!!$item->categorynames!!}</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="9" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="9" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('availablevendor.html') }}'; // URL generated by Laravel route
                loadData1(page, url); // Call custom function with page number and URL
            };
        });


</script>

