@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td nowrap style="text-align:left;">{{ $item->productname }}</td>
	<td nowrap style="text-align:center;">{{ $item->barcode }}</td>
	<td nowrap style="text-align:center;">{{ $item->quantity }}</td>
	<td nowrap style="text-align:center;"><input type="checkbox" onclick="printContent('{{ route('print.content') }}',{{$item->printid}},'pname')" @if($item->pname==1) checked @endif></td>
	<td nowrap style="text-align:center;"><input type="checkbox" onclick="printContent('{{ route('print.content') }}',{{$item->printid}},'pmrp')" @if($item->pmrp==1) checked @endif></td>
	<td nowrap style="text-align:center;"><input type="checkbox" onclick="printContent('{{ route('print.content') }}',{{$item->printid}},'sp')" @if($item->sp==1) checked @endif></td>
	<td nowrap style="text-align:center;">{{ date('d\-m\-Y',strtotime($item->printdate)) }}</td>
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
        <a title="" class="myactionlink" onclick="deleteItem('barcode',{{ $item->printid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','BARCODE DETAIL DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
    <td nowrap style="text-align:center;">
        <a href="{{ route('barcode.printing',$item->printid) }}" target="_blank" title=""><i class="fa fa-print"></i></a>
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="10" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        SORRY!<br>
        THE SYSTEM DID NOT FIND THE DATA YOU ARE LOOKING FOR.
    </td>
</tr>
@else
<tr>
<td colspan="10" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('unit.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

