@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td nowrap style="text-align:left;">{{ $item->branchname }}</td>
	<td nowrap style="text-align:left;">{{ $item->branchcode }}</td>
	<td nowrap style="text-align:left;">{{ $item->contact1 }}</td>
	<td nowrap style="text-align:left;">{{ $item->contact2 }}</td>
	<td nowrap style="text-align:left;">{{ $item->branchemail }}</td>
	<td nowrap style="text-align:left;">{{ $item->branchpannumber }}</td>
	<td nowrap style="text-align:left;">{{ $item->branchgstnumber }}</td>
	<td nowrap style="text-align:left;">{{ $item->statename }}</td>
	<td nowrap style="text-align:left;">{{ $item->cityname }}</td>
	<td nowrap style="text-align:left;">{{ $item->district }}</td>
	<td nowrap style="text-align:left;">{{ $item->postalcode }}</td>
	<td nowrap style="text-align:left;">{{ $item->completeaddress }}</td>
	<td nowrap style="text-align:left;">{{ $item->bankname }}</td>
	<td nowrap style="text-align:left;">{{ $item->bankaccount }}</td>
	<td nowrap style="text-align:left;">{{ $item->ifsccode }}</td>
	<td nowrap style="text-align:left;">{{ $item->bankbranch }}</td>
	<td nowrap style="text-align:left;">{{ $item->operatingcityname }}</td>
	<td nowrap style="text-align:left;">{!! $item->departments !!}</td>
	<td nowrap style="text-align:left;">{!! $item->categories !!}</td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.branch',Crypt::encrypt($item->branchid)) }}" title="" class="myactionlink"><i class="fa fa-edit"></i></a></td>
	@endif
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
        <a title="" class="myactionlink" onclick="deleteItem('branch','{{ Crypt::encrypt($item->branchid)}}',{{ $i }},'{{ __('messages.confirmation') }}','{{ __('messages.deleted') }}')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="22" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="22" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('branch.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

