@php
$i=1;
@endphp
@foreach ($data as $item)
<tr class="myheadbg">
	<td colspan="2">{{ $i++ }}) {{ $item->category }} | {{__('labels.displayorder')}} : {{ $item->displayorder }}
	<span style="float:right; margin-right:10px;">
	@if(in_array(3,Session::get('actions')))
        <a title="" class="myactionlink" onclick="deleteItem('category','{{ Crypt::encrypt($item->categoryid)}}',{{ $i }},'{{__('messages.confirmation')}}','{{__('messages.deleted')}}')" title=""><i class="fa fa-trash" style="color:white!important;"></i>
        </a>
	@endif	
	</span>
	<span style="float:right; margin-right:15px;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.category',Crypt::encrypt($item->categoryid)) }}" title="" class="myactionlink"><i class="fa fa-edit" style="color:white!important;"></i></a>
	@endif	
	</span>
	</td>
</tr>
<tr>
	<td style="width:150px; text-align:center;">
	@if($item->categoryicon!='')
        <a href="{{ asset('storage/'.$item->categoryicon) }}" target="_blank">
			<img src="{{ asset('storage/'.$item->categoryicon) }}" alt="Uploaded Image" style="width:150px; position:relative;">
		</a>
	@else
		<img src="{{ asset('storage/uploads/images/avatar.png') }}" alt="Uploaded Image" style="width:150px; position:relative;">
	@endif
	</td>
	<td style="padding:2px;">
		<table class="mytable" border="1">
			<tr>
				<td class="mybgtd" style="width:130px;" nowrap>{{__('labels.parentcategory')}}</td>
				<td colspan="5">{{$item->parentcategory}}</td>
			</tr>
			<tr>
				<td class="mybgtd" style="width:130px;">{{__('labels.categoryname')}}</td>
				<td nowrap colspan="5">{{$item->category}}</td>
			</tr>
			<tr>
				<td class="mybgtd" style="width:130px;" nowrap>{{__('labels.categorystatus')}}</td>
				<td colspan="5">@if($item->categorystatus==1) {{'ACTIVE'}} @else {{'IN ACTIVE'}} @endif</td>
			</tr>
			<tr>
				<td class="mybgtd" style="width:130px;">{{__('labels.metakeywords')}}</td>
				<td colspan="5">{{$item->metakeywords}}</td>
			</tr>
			<tr>
				<td class="mybgtd" style="width:130px;">{{__('labels.metadescription')}}</td>
				<td colspan="5">{{$item->metadescription}}</td>
			</tr>
			<tr>
				<td class="mybgtd" style="width:130px;" nowrap>{{__('labels.categorypage')}}</td>
				<td style="padding:0px; width:100px;" nowrap>
				@if($item->categorypage!='')
				<a href="{{ asset('storage/'.$item->categorypage) }}" target="_blank">
					<button type="button" class="btn btn-info mygridbtn" style="width:100%;"><i class="fa fa-download"></i> {{__('common.view')}}</button>
				</a>
				@endif
				</td>
				<td colspan="4"></td>
			</tr>
		</table>
	</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="2" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}}
    </td>
</tr>
@else
<tr>
<td colspan="2" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('category.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

