@php
$i=1
@endphp
@foreach ($data as $item)
<tr id="item-{{ $i }}">
    <td style="width:30px;" class="myrectd" nowrap>{{ $i++ }}</td>
	<td nowrap style="text-align:center;">{{ $item->servicetitle }}</td>

    <td nowrap style="text-align:center;">
    <a href="{{ asset('storage/'.$item->sliderimage) }}" target="_blank">
		<img src="{{ asset('storage/'.$item->sliderimage) }}" alt="Uploaded Image" style="width:100%; position:relative;">
	</a>
    </td>
	<td nowrap style="text-align:center;">
		<input type="checkbox" name="" id="" @if($item->isactive)==1) checked @endif onclick="SetActiveInactive('{{ route('setactive.cityslider') }}','{{ Crypt::encrypt($item->citysliderid)}}',{{$i}})"><br>
		<span id="{{$i}}" style="display:none;">
			<i class="fa fa-check-circle" style="color:green; font-size:18px;"></i><br>UPDATED
		</span>
	</td>
	<td nowrap style="text-align:center;">
		<input type="text" name="" id="" value="{{ $item->displayorder }}" class="selectbx" style="width:100%;" onchange="SetDisplayOrder('{{ route('setdisplay.cityslider') }}','{{ Crypt::encrypt($item->citysliderid)}}',{{$i}},this.value)"><br>
		<span id="d{{$i}}" style="display:none;">
			<i class="fa fa-check-circle" style="color:green; font-size:18px;"></i><br>UPDATED
		</span>

	</td>	
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.cityslider',Crypt::encrypt($item->citysliderid)) }}" title="" class="myactionlink"><i class="fa fa-edit"></i></a></td>
	@endif
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
        <a title="" class="myactionlink" onclick="deleteItem('cityslider','{{ Crypt::encrypt($item->citysliderid)}}',{{ $i }},'{{ __('messages.confirmation') }}','{{ __('messages.deleted') }}')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="7" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}}
    </td>
</tr>
@else
<tr>
<td colspan="7" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('cityslider.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

