@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td nowrap>{{ $item->name }}</td>
	<td nowrap>{{ $item->designation }}</td>
	<td nowrap>{{ $item->department }}</td>
	<td nowrap>{{ $item->mobilenumber }}</td>
	<td nowrap>{{ $item->email }}</td>
    <td nowrap style="text-align:center;">
	@permission('update.committeemember')
		<a href="{{ route('edit.committeemember',Crypt::encrypt($item->memberid)) }}" title=""><i class="fa fa-edit"></i></a></td>
	@endpermission
    <td nowrap style="text-align:center;">
	@permission('delete.committeemember')
        <a title="" onclick="deleteItem('committeemember','{{ Crypt::encrypt($item->memberid) }}',{{ $i }},'{{ __('messages.confirmation') }}','{{ __('messages.deleted') }}')" title=""><i class="fa fa-trash"></i>
        </a>
	@endpermission
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="8" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="8" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('committeemember.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

