@php
use Illuminate\Support\Facades\DB;
$i=1
@endphp
<tr>
	<td colspan="9">
		<span class="label label-primary"><input type="radio" onclick="loadData(1,'{{ route('customerorder.html') }}');" name="orderstatus" value="0" @if($orderstatus==0) checked @endif> PENDING <span class="badge badge-warning">{{$counts->pending}}</span></span>

		<span class="label label-primary"><input type="radio" onclick="loadData(1,'{{ route('customerorder.html') }}');" name="orderstatus" value="1" @if($orderstatus==1) checked @endif> ASSIGNED <span class="badge badge-warning">{{$counts->assigned}}</span></span>

		<span class="label label-primary"><input type="radio" onclick="loadData(1,'{{ route('customerorder.html') }}');" name="orderstatus" value="2" @if($orderstatus==2) checked @endif> STARTED <span class="badge badge-warning">{{$counts->started}}</span></span>

		<span class="label label-primary"><input type="radio" onclick="loadData(1,'{{ route('customerorder.html') }}');" name="orderstatus" value="4" @if($orderstatus==4) checked @endif> ON HOLD <span class="badge badge-warning">{{$counts->onhold}}</span></span>

		<span class="label label-primary"><input type="radio" onclick="loadData(1,'{{ route('customerorder.html') }}');" name="orderstatus" value="3" @if($orderstatus==3) checked @endif> COMPLETED <span class="badge badge-warning">{{$counts->completed}}</span></span>

		<span class="label label-primary"><input type="radio" onclick="loadData(1,'{{ route('customerorder.html') }}');" name="orderstatus" value="-1" @if($orderstatus==-1) checked @endif> CANCELLED <span class="badge badge-warning">{{$counts->cancelled}}</span></span>

		<span class="label label-primary"><input type="radio" onclick="loadData(1,'{{ route('customerorder.html') }}');" name="orderstatus" value="10" @if($orderstatus==10) checked @endif> UN PAID <span class="badge badge-warning">{{$counts->unpaid}}</span></span>
	</td>
</tr>
<tr class="myheadbg">
	<td class="center white" style="width:50px;">S.NO.</td>
	<td class="lefttdwhite">CUSTOMER NAME</td>
	<td class="center">MOBILE NUMBER</td>
	<td class="lefttdwhite white">EMAIL</td>
	<td class="center white">ORDER DATE</td>
	<td class="center white">SERVICE DATE</td>
	<td class="center white">SLOT TIME</td>
	<td class="center white">AMOUNT</td>
	<td class="center white"></td>
</tr>

@foreach($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td nowrap class="center">{{ $i++ }}</td>
	<td nowrap class="lefttdwhite">{{ $item->name }} {{ $item->middlename }} {{ $item->lastname }}</td>
	<td nowrap class="center">{{ $item->mobilenumber }}</td>
	<td nowrap class="lefttdwhite">{{ e($item->email) }}</td>
	<td nowrap class="center">{{ date('d\-m\-Y, h:i A',strtotime($item->creation_date)) }}</td>
	<td nowrap class="center">{{ date('d\-m\-Y',strtotime($item->servicedate)) }}</td>
	<td nowrap class="center">{{ date('h:i A',strtotime($item->slottime)) }}</td>
	<td nowrap class="center">{{$item->netpayable}}</td>
	<td nowrap style="padding:0px!important;">
		<button type="button" class="btn btn-info mygridbtn orderrecord" style="width:100%;" data-id="{{ $item->orderid }}">
			<i class="fa fa-eye"></i> VIEW
		</button>
	</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td style="text-align:center;" colspan="9">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td style="text-align:right;" colspan="9">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('order.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

