@php
$i=1
@endphp
@foreach($data as $item)
<tr id="item-{{ $i }}">
    <td class="myheadbg" nowrap colspan="2">
		{{ $i++ }}) Account Login Id : {{$item->mobilenumber}} 
		<span style="margin-right:10px; float:right;">
		@if(in_array(3,Session::get('actions')))
			<a title="" class="myactionlink" onclick="deleteItem('customer','{{ Crypt::encrypt($item->customerid)}}',{{ $i }},'{{__('messages.confirmation')}}','{{__('messages.deleted')}}')" title="">
				<i class="fa fa-trash" style="color:white!important;"></i>
			</a>
		@endif
		</span>
		<span style="margin-right:15px; float:right;">
		@if(in_array(2,Session::get('actions')))
			<a href="{{ route('edit.customer',Crypt::encrypt($item->customerid)) }}" title="" class="myactionlink">
				<i class="fa fa-edit" style="color:white!important;"></i>
			</a>
		@endif	
		</span>
		
		
	</td>
</tr>
<tr>
    <td nowrap style="width:100px;">
	@if($item->profilepic!='')
        <a href="{{ asset('storage/'.$item->profilepic) }}" target="_blank">
			<img src="{{ asset('storage/'.$item->profilepic) }}" alt="Uploaded Image" style="width:100px;">
		</a>
	@else
		<img src="{{ asset('storage/uploads/images/avatar.png') }}" alt="Uploaded Image" style="width:100px;">
	@endif
    </td>
	<td>
		<table class="mytable" border="1">
			<tr>
				<td class="mybgtd" colspan="3"><b>{{__('labels.basicdetail')}}</b></td>
			</tr>
			<tr>
				<td class="mybgtd">{{__('labels.name')}}</td>
				<td class="mybgtd">{{__('labels.mobilenumber')}}</td>
				<td class="mybgtd">{{__('labels.email')}}</td>
			</tr>
			<tr>
				<td class="" style="vertical-align:top;">{{$item->name}}</td>
				<td class="" style="vertical-align:top;">{{$item->mobilenumber}}</td>
				<td class="" style="vertical-align:top;">{{strtolower($item->email)}}</td>
			</tr>
			<tr>
				<td class="mybgtd" colspan="3"><b>{{__('labels.addressdetail')}}</b></td>
			</tr>
			<tr>
				<td class="mybgtd">{{__('labels.statename')}}</td>
				<td class="mybgtd">{{__('labels.cityname')}}</td>
				<td class="mybgtd">{{__('labels.postalcode')}}</td>
			</tr>
			<tr>
				<td class="" style="vertical-align:top;">{{$item->statename}}</td>
				<td class="" style="vertical-align:top;">{{$item->cityname}}</td>
				<td class="" style="vertical-align:top;">{{$item->postalcode}}</td>
			</tr>
			<tr>
				<td class="" style="vertical-align:top;" colspan="3">Address : {{$item->completeaddress}}</td>
			</tr>
		</table>
	</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('customer.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>
