@php
 $i = 1;
@endphp
@foreach($data as $item)
    <tr class="mytr" id="item-{{ $i }}">
        <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
        <td class="first-column-name">
			{{ ucwords(strtolower($item->departmentname)) }} [{{ ucwords(strtoupper($item->shortname)) }}]<br>{{$item->officialemail}}
		</td>
        <td style="width:200px;">{{ $item->mobilenumber }}</td>
        <td>{{ $item->email }}<br>{{$item->pass_word}}</td>
        <td>{{ $item->address }}</td>

        <td nowrap style="text-align: center; padding: 0px; width:100px;">
		@permission('update.departmentrequest')
            <a href="{{ route('edit.departmentrequest', Crypt::encrypt($item->departmentid)) }}" class="btn myfrmbtn smbtn">Edit</a>
		@endpermission
        </td>
    </tr>
@endforeach
@if($i == 1)
    <tr>
        <td colspan="6" style="text-align:center;">
            <br>
            @include('admin.body.actionmessage')
        </td>
    </tr>
@else
    <tr>
        <td colspan="6" style="text-align:right;">
            {{ $data->links('vendor.pagination.default') }}
        </td>
    </tr>
@endif

<script>
    const paginationLinks = document.querySelectorAll('.pagination a');
    paginationLinks.forEach(link => {
        link.onclick = function (event) {
            event.preventDefault(); // Prevent default link behavior
            const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
            const url = '{{ route('departmentrequest.html') }}'; // URL generated by Laravel route
            loadData(page, url); // Call custom function with page number and URL
        };
    });
</script>