@php
$i=1;
@endphp
@foreach($data as $item)
<tr id="item">
    <td nowrap class="center">{{ $i++ }}</td>
	<td nowrap>{{strtoupper($item->vendorname)}} {{strtoupper($item->vendormiddlename)}} {{strtoupper($item->vendorlastname)}}</td>	
	<td nowrap>{{ $item->receiptnumber }}
	@if($item->receiptfile!='')
		<a href="{{ asset('storage/receipts/'.$item->receiptfile) }}" target="_blank" style="text-decoration:none;">
			<i class="fa fa-print"></i>
		</a> 	
	@endif
	</td>
	<td nowrap>{{ date('d\-m\-Y h:i A',strtotime($item->paymentdatetime)) }}</td>
	<td nowrap>{{ $item->paymentstatus }}</td>
	<td nowrap>{{ number_format($item->taxable,'2','.','') }}</td>
	<td nowrap>{{ $item->dramount }}</td>
	<td nowrap>{{ $item->taxable-$item->dramount }}</td>
	<td nowrap>
	@if($item->servicetitle!='')
		EARNING AMOUNT FOR {{ strtoupper($item->servicetitle) }} - TAXABLE AMOUNT {{number_format($item->taxable)}}
	@endif
	</td>

</tr>
@endforeach
@if($i==1)
<tr>
    <td style="text-align:center;" colspan="9">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td style="text-align:right;" colspan="9">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('earning.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

