@php
	$i = 1;
	
@endphp
@foreach ($data as $item)
	@php

		$flags = [];
		$buttons = [];


		$buttons[] = [
			'label' => 'View File',
			'href' => route('view.uploadedfile', Crypt::encrypt($item->authorizationletter)),
			'icon' => 'fa-hand-o-right',
			'target' => '_blank',
		];

		$buttons[] = [
			'label' => 'View EoI',
			'href' => route('prepare.draft', Crypt::encrypt($item->requestid)),
			'icon' => 'fa-edit',
		];
		$flags[] = ['label' => 'Cancelled', 'icon' => 'fa-exclamation-circle', 'class' => 'eoi-flag--info'];

		if ($item->isinprebid) {
			$buttons[] = [
				'label' => 'Pre-bid Enquiry',
				'href' => route('prebidenquiry.list', Crypt::encrypt($item->requestid)),
				'icon' => 'fa-hand-o-right',
			];
		}

		if($item->eoistatus>=3)
		{
			$buttons[] = [
				'label' => 'EoI Published',
				'onclick' =>  "ShowFirms('".Crypt::encrypt($item->requestid)."')",
				'icon' => 'fa-bullhorn',
			];
			
			if($item->eoi_file!='')
			{
				$buttons[] = [
					'label' => 'Download EoI',
					'href' => route('view.uploadedfile', Crypt::encrypt($item->eoi_file)),
					'icon' => 'fa-download',
					'target' => '_blank',
				];
			}			
		}
		if($item->eoistatus==4)
		{
			$buttons[] = [
				'label' => 'Vendors',
				'href' => route('view.pptresumes', Crypt::encrypt($item->requestid)),
				'icon' => 'fa-users',
			];			
		}
	@endphp

	@php
		$serial = $i++;
	@endphp
	<tr class="eoi-row" id="item-{{ $serial }}">
		<td class="padding-10 eoi-card-cell">
			<div class="eoi-card">
				<div class="eoi-header">
					<div class="eoi-main">
						<div class="eoi-number-line">
							<div class="eoi-sno">{{ $serial }}.</div>
							<div class="eoi-project">{{ $item->projecttitle }}</div>
							
							@if(count($flags))
								<div class="eoi-flags">
									@foreach($flags as $flag)
										<span class="eoi-flag {{ $flag['class'] ?? '' }}">
											<i class="fa {{ $flag['icon'] }}"></i> {{ $flag['label'] }}
										</span>
									@endforeach
								</div>
							@endif
						</div>
						<div class="eoi-number">{{ $item->eoinumber }} [@if($item->tier_choice==1) Tier - 1 @elseif($item->tier_choice==2) Tier - 2 @else Both @endif]</div>
					</div>
					@if(count($buttons))
						<div class="eoi-actions">
							@foreach($buttons as $btn)
								<a @if(!empty($btn['href'])) href="{{ $btn['href'] }}" @endif class="eoi-btn action-a @if(!empty($btn['class'])) {{ $btn['class'] }} @endif" @if(!empty($btn['target']))
								target="{{ $btn['target'] }}" @endif @if(!empty($btn['data-url'])) data-url="{{ $btn['data-url'] }}" @endif @if(!empty($btn['onclick'])) onclick={{ $btn['onclick'] }} @endif>
									<i class="fa {{ $btn['icon'] }}"></i> {{ $btn['label'] }}
								</a>
							@endforeach
						</div>
					@endif
				</div>

				<div class="eoi-progress">
					<div class="eoi-progress-label width-150">Cancellation Request Date</div>
					<div class="eoi-progress-text">: {{ date('d-m-Y, h:i A',strtotime($item->canReqOn)) }}</div>
				</div>

				<div class="eoi-progress">
					<div class="eoi-progress-label"><b>Reason</b><br>{!!$item->cancellation_remark!!}
						@if($item->cancellation_attachment!='')
						<br>
						<a href="{{ route('view.uploadedfile',Crypt::encrypt($item->cancellation_attachment))}}" class="eoi-btn action-a" target="_blank" style="outline:none;">
							<i class="fa fa-file-o"></i> View File
						</a>
						
						@endif
					
					</div>
				</div>

			</div>
		</td>
	</tr>
@endforeach
@if($i == 1)
	<tr>
		<td class="padding-10" style="text-align:center;">
			<br>
			<i class="fa fa-warning blue nodata"></i><br>
			{!! __('messages.sorry') !!}
		</td>
	</tr>
@else
	<tr>
		<td style="text-align:right;">
			{{ $data->links('vendor.pagination.default') }}
		</td>
	</tr>
@endif

<script>
	const paginationLinks = document.querySelectorAll('.pagination a');
	paginationLinks.forEach(link => {
		link.onclick = function (event) {
			event.preventDefault(); // Prevent default link behavior
			const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
			const url = '{{ route('eoicancel.html') }}'; // URL generated by Laravel route
			loadData(page, url); // Call custom function with page number and URL
		};
	});

</script>
