@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td nowrap style="text-align:center;">{{ date('d\-m\-Y',strtotime($item->frmdate)) }}</td>
	<td nowrap style="text-align:center;">{{ date('d\-m\-Y',strtotime($item->todate)) }}</td>
	<td nowrap style="text-align:center;">{{ $item->days }}</td>
	<td nowrap style="text-align:left;">{{ $item->remark }}</td>
	<td nowrap style="text-align:center;">@if($item->isapproved==0){{ 'PENDING' }} @elseif($item->isapproved==1) {{'APPROVED'}} @endif</td>
	<td nowrap style="text-align:left;">{{ $item->approvedbyname }}</td>
	<td nowrap style="text-align:left;">{{ $item->approvalremark }}</td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		@if($item->isapproved==0)
		<a href="{{ route('edit.leave',$item->recordid) }}" title="" class="myactionlink"><i class="fa fa-edit"></i></a>
		@else
		<i class="fa fa-info-circle" title="APPROVED"></i>
		@endif
	@endif
	</td>
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
		@if($item->isapproved==0)
        <a title="" class="myactionlink" onclick="deleteItem('leave',{{ $item->recordid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','LEAVE RECORD DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
		@else
		<i class="fa fa-info-circle" title="APPROVED"></i>
		@endif
	@endif
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="10" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        SORRY!<br>
        THE SYSTEM DID NOT FIND THE DATA YOU ARE LOOKING FOR.
    </td>
</tr>
@else
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('leave.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

