@php
$i=1
@endphp
@foreach ($data as $item)
<tr>
    <td class="text-center v-top" rowspan="4" nowrap>{{ $i++ }}</td>
    <td>{{ date('d\-m\-Y',strtotime($item->notification_date)) }}</td>
	<td>{{ $item->notification_title }}</td>
	<td>{!! $item->notification_content !!}</td>
</tr>
<tr>
	<td colspan="3">Department<br>{!!$item->departments!!}</td>
</tr>
<tr>
	<td colspan="3">Project Manager<br>{!!$item->managers!!}</td>
</tr>
<tr>
	<td colspan="3">Firms<br>{!!$item->vendors!!}</td>
</tr>

@endforeach
@if($i==1)
<tr>
    <td colspan="4" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="4" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('notification.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

