@php
$i=1
@endphp
@foreach ($data as $item)
<tr>
    <td class="text-center v-top" nowrap>{{ $i++ }}</td>
    <td class="v-top">{{ date('d\-m\-Y',strtotime($item->notification_date)) }}</td>
	<td class="v-top">{{ $item->notification_title }}</td>
	<td class="v-top" style="position:relative;">{!! $item->notification_content !!}
	@if($item->notification_attachment!='')
		<button type="button" class="eoi-btn action-a">
		<a href="{{ route('view.uploadedfile', Crypt::encrypt($item->notification_attachment)) }}" target="_blank" style="text-decoration:none; outline:none;">
			<span class="fa fa-download"></span> View File
		</a>		
		</button>
	@endif
	</td>
</tr>
@endforeach
@if($i==1)
<tr><td colspan="4" class="center">--No Record Found--</td></tr>
@else
<tr>
<td colspan="4" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('viewnotification.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

