@php
$i=1;
@endphp
@foreach($data as $item)
<tr class="" id="item-{{ $i }}">
    <td nowrap class="center lh-30 v-top">{{ $loop->iteration }}</td>
	<td nowrap class="lh-30 v-top">{{ $item->voucher_number }}<br>{{ $item->ordernumber }}<br>{{ ucwords(strtolower($item->departmentname)) }}<br>{{ ucwords(strtolower($item->companyname)) }}</td>
	<td nowrap class="lh-30 v-top form-label">
		{{ $item->invoice_number }}
		@if($item->invoice_file!='')
		<br>
		<a href="{{ asset('storage/'.$item->invoice_file) }}" target="_blank">
			<span class="label label-white middle animated flipInX delay-02 f-s-10 form-label span-content" style="">
				<i class="fa fa-file-pdf-o"></i> Invoice File
			</span>
		</a>
		@endif
		
	</td>
	<td nowrap class="center lh-30 v-top">{{ date('d\-m\-Y',strtotime($item->invoice_date)) }}</td>
	<td nowrap class="lh-30 v-top" style="text-align:right;">{{ $item->invoice_amount }}</td>
	<td nowrap class="lh-30 v-top" style="text-align:right;">{{ $item->tax_value }}</td>
	<td nowrap class="lh-30 v-top" style="text-align:right;">
		{{ $item->net_invoice_value }}
		<br>
		<span class="label label-white middle animated flipInX delay-02 f-s-10 form-label span-content" style="">
			<i class="fa fa-inr"></i> Pay Amount
		</span>
	</td>
</tr>
@endforeach
@if($data->count()==0)
<tr>
    <td colspan="7" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="7" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('admininvoice.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

