@php
$i=1;
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $loop->iteration }}</td>
	<td>{{ $item->name }}
	@if($item->isReleased==0)
	<br>
	<a class="eoi-btn action-a process-release" data-url="{{route('process.release',Crypt::encrypt($item->recordid))}}" style="cursor:pointer;">
		<i class="fa fa-hand-o-right"></i> Process Release
	</a>
	@else
	<br>
	<span class="eoi-flag eoi-flag--success">
		<i class="fa fa-thumbs-up"></i> Released
	</span>	
	@endif
	
	</td>
	<td>{{ $item->companyname }}</td>
	<td>{{ $item->role }}</td>
	<td>{{ $item->sectorname }}</td>
	<td>{{ $item->consultantposition }}</td>
	<td  style="white-space:nowrap;">{{ date('d\-m\-Y',strtotime($item->creationdate)) }}</td>
	<td style="white-space:nowrap;">{{ date('d\-m\-Y',strtotime($item->lastdate)) }}</td>
</tr>
@endforeach
@if($data->count()==0)
<tr>
    <td colspan="8" style="text-align:center;">
        <br>
		@include('admin.body.actionmessage')
    </td>
</tr>
@else
<tr>
<td colspan="8" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('resources.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });		
</script>

<script src="{{ asset('panel/assets/js/datatablePaginationWithFilter.js') }}"></script>
<script>

$('.process-release').on('click', function () {

    var docUrl = $(this).data('url');
    bootbox.confirm('Are you sure you want to process this release?', function (result)
	{
        if(result)
		{
            $.get(docUrl, {}, function (data)
			{
                if (data.status === 200)
				{
                    bootbox.alert(data.message);
					loadData(1,'{{ route("releasing.html") }}');
                }
				else
				{
                    bootbox.alert('<span style="color:red;">'+data.message+'</span>');
                }

            }).fail(function () {
                bootbox.alert('Server error. Please try again later.');
            });

        }
    });

});

document.querySelectorAll('.format-indian').forEach(function(el) {
    el.innerText = formatIndianNumber(el.dataset.value);
});

</script>


