@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
    <td nowrap>{{ $item->ratelist_name }}</td>
	<td nowrap>{{ $item->sectorname }}</td>
	<td nowrap>{{ $item->consultantposition }}</td>
	<td nowrap>{{ $item->tiername }}</td>
	<td nowrap>{{ $item->workexperience }}</td>
	<td nowrap>@if($item->experiencelevel!=0) {{ $item->experiencelevel }} @endif</td>
	<td nowrap>{{ $item->remuneration }}</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="8" style="text-align:center;">
        <br>
		@include('admin.body.actionmessage')
    </td>
</tr>
@else
<tr>
<td colspan="8" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('remuneration.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

