@php
$i=1;
@endphp
@foreach($data as $item)
<tr class="" id="item-{{ $i }}">
    <td nowrap class="center lh-30 v-top">{{ $loop->iteration }}</td>
	<td class="lh-30 v-top">{{ $item->departmentname }}</td>
	<td nowrap class="lh-30 v-top form-label">{{ $item->ordernumber }}<br>{{ $item->companyname }}</td>
	<td class="center lh-30 v-top">{{ date('d\-m\-Y',strtotime($item->orderdate)) }}</td>
	<td class="lh-30 v-top format-indian" style="text-align:right;">{{ $item->workorderamount}}</td>
	<td class="lh-30 v-top format-indian" style="text-align:right;">0<br>
		<span class="label label-white middle animated flipInX delay-02 f-s-10 form-label span-content" style="">
			<i class="fa fa-inr"></i> Add Payment Request
		</span>
	
	</td>
	<td class="lh-30 v-top format-indian" style="text-align:right;">0</td>
	<td class="lh-30 v-top format-indian" style="text-align:right;">{{ $item->workorderamount}}</td>
</tr>
@endforeach
@if($data->count()==0)
<tr>
    <td colspan="8" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="8" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('orders.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

