@php
$i=1;

@endphp
@foreach ($data as $item)

@php
$serial = $i++;
@endphp

<tr class="eoi-row" id="item-{{ $serial }}">
	<td class="padding-2 eoi-card-cell" style="@if($serial%2!=0) background-color:white!important; @endif">
		<div class="eoi-card">
			<div class="eoi-header">
				<div class="eoi-main">
					<div class="eoi-number-line">
						<div class="eoi-sno">{{ $serial }}.</div>
						<div class="eoi-project">{{ $item->name }} @if($item->eoinumber)| EoI Number : {{ $item->eoinumber }}@endif @if($item->duration) @endif</div>
					</div>
					<div class="eoi-number mt-10" style="padding-left:18px!important;">
						Order Date : {{ date('d\-m\-Y',strtotime($item->orderdate)) }} | Order Number : {{ $item->ordernumber }} @if($item->deployed_date) | Deployed Date : {{ date('d\-m\-Y',strtotime($item->deployed_date)) }} @endif
					</div>
				</div>
				@permission('store.release')
				<a class="eoi-btn action-a release-resource" data-url="{{route('release.resource',Crypt::encrypt($item->resourceid))}}" style="cursor:pointer;">
					<i class="fa fa-hand-o-right"></i> Release
				</a>
				@endpermission
			</div>
			<table style="border:none!important;">
				<tr>
					<td style="padding:3px!important; border:none!important;">Firm Name</td>
					<td style="padding:3px!important; border:none!important; font-weight:500;"> : {{ $item->companyname }}</td>
				</tr>
				<tr>
					<td style="padding:3px!important; border:none!important;" nowrap>Department / Project Manager</td>
					<td style="padding:3px!important; border:none!important; font-weight:500;"> : {{ $item->departmentname }}</td>
				</tr>
				<tr>
					<td style="padding:3px!important; border:none!important; vertical-align:top;">Project Name</td>
					<td style="padding:3px!important; border:none!important;"> : {{ $item->project_name }}</td>
				</tr>
				@if($item->consultantposition)
				<tr>
					<td style="padding:3px!important; border:none!important;">Position</td>
					<td style="padding:3px!important; border:none!important;"> : {{ $item->consultantposition }}</td>
				</tr>
				<tr>
					<td style="padding:3px!important; border:none!important;">Sector</td>
					<td style="padding:3px!important; border:none!important;"> : {{ $item->sectorname }}</td>
				</tr>
				@else
				<tr>
					<td style="padding:3px!important; border:none!important;">Role</td>
					<td style="padding:3px!important; border:none!important;"> : {{ $item->role }}</td>
				</tr>
				@endif
				<tr>
					<td style="padding:3px!important; border:none!important;">Remuneration (per month)</td>
					<td style="padding:3px!important; border:none!important;"> : {{ number_format($item->remuneration,'2','.','') }} INR</td>
				</tr>
			</table>
		</div>
		
	</td>
</tr>
@endforeach
@if($data->count()==0)
<tr>
    <td style="text-align:center;">
        <br>
		@include('admin.body.actionmessage')
    </td>
</tr>
@else
<tr>
<td style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('resources.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });


$('.release-resource').on('click', function () {
    var docUrl = $(this).data('url');
    var params = {
    };
	
    $(".modal-xl").css("width", "90%");
    $('#releaseModal').modal('show');
	$('#releaseData').html("Please wait...");
    $.get(docUrl, params, function (data) {
        setTimeout(function () {
            $('#releaseData').html(data.releaseform);
        }, 1000);
    }).fail(function () {
        $('#releaseData').html('<p class="text-danger">Failed to load EoI.</p>');
    });
	
});
		
</script>

<script src="{{ asset('panel/assets/js/datatablePaginationWithFilter.js') }}"></script>
<script>
document.querySelectorAll('.format-indian').forEach(function(el) {
    el.innerText = formatIndianNumber(el.dataset.value);
});

</script>


