@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }} @if($item->actionremark!='') <i class="fa fa-info-circle text-default" onclick="ShowRemark('{{$item->actionremark}}')"></i> @endif</td>
	<td nowrap style="text-align:left;">{{ $item->name }}</td>
	<td nowrap style="text-align:center;">{{ date('d\-m\-Y',strtotime($item->paymentdate)) }}</td>
	<td nowrap style="text-align:center;">{{ $item->paymentmode }}</td>
	<td nowrap style="text-align:center;">{{ $item->receiptnumber }}</td>
	<td nowrap style="text-align:center;">{{ $item->utrno }}</td>
	<td nowrap style="text-align:center;">{{ $item->batchneft }}</td>
	<td nowrap style="text-align:center;">{{ $item->chequenumber }}</td>
	<td nowrap style="text-align:center;">@if($item->chequedate!='') {{ date('d\-m\-Y',strtotime($item->chequedate)) }} @endif</td>
	<td nowrap style="text-align:center;">{{ $item->amount }}</td>
	<td nowrap style="text-align:left;">{{ $item->remark }}</td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.salespayment',$item->paymentid) }}" title="" class="myactionlink"><i class="fa fa-edit"></i></a></td>
	@endif
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
        <a title="" class="myactionlink" onclick="deleteItem('salespayment',{{ $item->paymentid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','SALES PAYMENT DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
</tr>
@if($item->actionremark!='')
<tr id="{{$i}}" class="lst" style="display:none;"><td colspan="7">{!!$item->actionremark!!}</td></tr>
@endif
@endforeach
@if($i==1)
<tr>
    <td colspan="14" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        SORRY!<br>
        THE SYSTEM DID NOT FIND THE DATA YOU ARE LOOKING FOR.
    </td>
</tr>
@else
<tr>
<td colspan="13" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('salespayment.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

