@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}
	</td>
	<td nowrap style="text-align:left;">{{ $item->branchname }}</td>
	<td nowrap style="text-align:left;">{{ ucwords(strtolower($item->label)) }}</td>
	<td nowrap style="text-align:left;">{{ $item->mobilenumber }}</td>
	<td nowrap class="center">@if($item->paymentdate!='') {{ date('d\-m\-Y',strtotime($item->paymentdate)) }} @endif</td>
	<td nowrap style="text-align:left;">{{ $item->paymentmode }} | {{ strtoupper($item->paymentstatus) }}</td>	
	<td nowrap class="center">{{ $item->amount }}</td>
	<td nowrap style="text-align:left;">{{ $item->paymentremark }} {{ $item->razorpay_payment_id }}</td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		@if($item->payment_link_id=='')
		<a href="{{ route('edit.securitydeposit',Crypt::encrypt($item->depositid)) }}" title="" class="myactionlink"><i class="fa fa-edit"></i></a>
		@endif
	@endif
	</td>	
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
        <a title="" class="myactionlink" onclick="deleteItem('securitydeposit','{{ Crypt::encrypt($item->depositid)}}',{{ $i }},'{{ __('messages.confirmation') }}','{{ __('messages.deleted') }}')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
	<td class="center">
	@if($item->paymentstatus=='paid')
		<a href="{{ asset('storage/deposits/'.$item->receiptnumber.'.pdf') }}" target="_blank">
			<i class="fa fa-print"></i>
		</a>
	@endif
	</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="12" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
		{!! __('messages.sorry') !!}}
    </td>
</tr>
@else
<tr>
<td colspan="11" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('securitydeposit.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

