@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
    <td nowrap>{{ ucwords(strtolower($item->servicetitle)) }}</td>
	<td nowrap style="padding:0px;">
		<input type="text" name="service{{$item->serviceid}}" id="service{{$item->serviceid}}" value="{{ $item->displayorder }}" onchange="UpdateServiceOrder(this.value,'{{ route('update.serviceorder') }}',{{$item->serviceid}})">
	</td>
</tr>
<tr class="tr{{$item->serviceid}}" style="display:none;"><td class="td{{$item->serviceid}}" colspan="3"></td></tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="3" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="3" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif
<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('servicelists.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

