@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
    <td nowrap>{{ $item->tagline }}</td>
	<td nowrap style="text-align:center;">{{ $item->displayorder }}</td>
	<td nowrap style="text-align:center;">
	<input type="checkbox" disabled @php if($item->isactive) echo 'checked'; else ''; @endphp>
	</td>
	<td nowrap style="text-align:center;">{{ date('d\-m\-Y, h:i A',strtotime($item->creationdate)) }}</td>
    <td nowrap style="text-align: left;">{{ $item->createdbyname }}</td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.tag',$item->tagid) }}" title=""><i class="fa fa-edit"></i></a>
	@endif
	</td>
	
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
        <a title="" onclick="deleteItem('tag',{{ $item->tagid}},{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','TAG LINE DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="8" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        SORRY!<br>
        THE SYSTEM DID NOT FIND THE DATA YOU ARE LOOKING FOR.
    </td>
</tr>
@else
<tr>
<td colspan="8" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('tag.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

