@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
    <td nowrap>{{ $item->districtname }}</td>
	<td nowrap>{{ $item->tehsilname }}</td>
	<td nowrap>{{ $item->tehsilcode }}</td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.tehsil',Crypt::encrypt($item->tehsilid)) }}" title=""><i class="fa fa-edit"></i></a>
	@endif
	</td>
    <td nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
        <a title="" onclick="deleteItem('tehsil','{{ Crypt::encrypt($item->tehsilid)}}',{{ $i }},'ARE YOU SURE YOU WANT TO DELETE THIS RECORD?','RECORD DELETED SUCCESSFULLY')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="6" style="text-align:center;">
        <br>
		@include('admin.body.actionmessage')
    </td>
</tr>
@else
<tr>
<td colspan="6" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('tehsil.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

