@php
$i=1
@endphp
@foreach ($data as $item)
<tr id="item-{{ $i }}">
    <td style="width:30px;" class="myrectd" nowrap>{{ $i++ }}</td>
    <td nowrap>{{ $item->name }}</td>
    <td nowrap>{{ $item->email }}<br>{{ $item->pass_word }}</td>
    <td nowrap>{{ $item->mobilenumber }}</td>
	<td nowrap class="width-100">
	@permission('set.userpermission')
		<a href="{{ route('set.userpermission',Crypt::encrypt($item->userid)) }}" title="">
			<button type="button" class="btn btn-info gridbtn width-100">Set Permission</button>
		</a>
	@endpermission
	</td>
    <td nowrap style="text-align:center; padding:0px;">
	@permission('update.user')
	<a href="{{ route('edit.user',Crypt::encrypt($item->userid)) }}" title="">
		<i class="fa fa-edit"></i>
	</a>
	@endpermission
	</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="6" style="text-align:center;">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        Sorry!<br>
        THE SYSTEM did not find the data you are looking for.
    </td>
</tr>
@endif
<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('users.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

