@php
$i=1;
@endphp
@foreach($data as $item)
<tr id="item-{{ $i }}">
    <td class="myheadbg" nowrap colspan="2">
		{{ $i++ }}) {{$item->name}} | Mob : {{$item->mobilenumber}} | Email :  	{{$item->email}} | Gender : {{$item->gender}} | DOB : @if($item->dob!='') {{date('d\-m\-Y',strtotime($item->dob))}} @endif | User Name : {{$item->username}}
		<span style="margin-right:10px; float:right;">
		@if(in_array(3,Session::get('actions')))
			<a title="" class="myactionlink" onclick="deleteItem('user','{{ Crypt::encrypt($item->userid)}}',{{ $i }},'{{__('messages.confirmation')}}','{{__('messages.deleted')}}')" title="">
				<i class="fa fa-trash" style="color:white!important;"></i>
			</a>
		@endif
		</span>
		<span style="margin-right:15px; float:right;">
		@if(in_array(2,Session::get('actions')))
			<a href="{{ route('edit.user',Crypt::encrypt($item->userid)) }}" title="" class="myactionlink">
				<i class="fa fa-edit" style="color:white!important;"></i>
			</a>
		@endif	
		</span>
		
		
	</td>
</tr>
<tr id="itemd-{{ $i-1 }}">
    <td nowrap style="width:100px;">
        <a href="{{ asset('storage/'.$item->profilepic) }}" target="_blank">
			<img src="{{ asset('storage/'.$item->profilepic) }}" alt="Uploaded Image" style="width:100px;">
		</a>
		
    </td>
	<td>
		<table class="mytable" border="1">
			<tr>
				<td class="mybgtd" colspan="4"><b>{{__('labels.employmentinformation')}}</b></td>
			</tr>
			<tr>
				<td class="mybgtd">{{__('labels.branchname')}}</td>
				<td class="mybgtd">{{__('labels.departmentname')}}</td>
				<td class="mybgtd">{{__('labels.designation')}}</td>
				<td class="mybgtd"></td>
			</tr>
			<tr>
				<td class="" style="vertical-align:top;">{!!$item->branchs!!}</td>
				<td class="" style="vertical-align:top;">{{$item->departmentname}}</td>
				<td class="" style="vertical-align:top;">{{$item->designationname}}</td>
				<td class=""></td>
			</tr>
			<tr>
				<td class="mybgtd" colspan="4"><b>{{__('labels.addressdetail')}}</b></td>
			</tr>
			<tr>
				<td class="mybgtd">{{__('labels.statename')}}</td>
				<td class="mybgtd">{{__('labels.cityname')}}</td>
				<td class="mybgtd">{{__('labels.postalcode')}}</td>
				<td class="mybgtd"></td>
			</tr>
			<tr>
				<td class="" style="vertical-align:top;">{{$item->statename}}</td>
				<td class="" style="vertical-align:top;">{{$item->cityname}}</td>
				<td class="" style="vertical-align:top;">{{$item->postalcode}}</td>
				<td class=""></td>
			</tr>
			<tr>
				<td class="" style="vertical-align:top;" colspan="4">Address : {{$item->address}}</td>
			</tr>
			<tr>
				<td class="mybgtd" colspan="4"><b>{{__('labels.bankdetail')}}</b></td>
			</tr>
			<tr>
				<td class="mybgtd">{{__('labels.bankname')}}</td>
				<td class="mybgtd">{{__('labels.accountnumber')}}</td>
				<td class="mybgtd">{{__('labels.ifsccode')}}</td>
				<td class="mybgtd">{{__('labels.branchname')}}</td>
			</tr>
			<tr>
				<td class="" style="vertical-align:top;">{{$item->bankname}}</td>
				<td class="" style="vertical-align:top;">{{$item->accountnumber}}</td>
				<td class="" style="vertical-align:top;">{{$item->ifsccode}}</td>
				<td class="" style="vertical-align:top;">{{$item->branchname}}</td>
			</tr>
		</table>
	</td>
</tr>

@endforeach

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('users.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>
