@php
$i=1;
$balance	=	$openingbalance;
@endphp
<tr id="item">
    <td nowrap colspan="6" style="text-align:right;">OPENING BALANCE</td>
	<td>{{$openingbalance}} INR</td>
	<td colspan="6"></td>
</tr>

@foreach($data as $item)
@php
	if($item->paymentstatus!='failed')
	{
		if($item->cramount!=0)
		$balance	=	$balance+$item->cramount;
		else
		$balance	=	$balance-$item->dramount;
	}
@endphp
<tr id="item">
    <td nowrap class="center">{{ $i++ }}</td>
	<td nowrap>{{ $item->name }} @if($item->middlename!='') {{ $item->middlename }} @endif  @if($item->lastname!='') {{ $item->lastname }} @endif</td>
	<td nowrap>{{ date('d\-m\-Y h:i A',strtotime($item->paymentdatetime)) }}</td>
	<td nowrap>@if($item->paymentmethod!='') {{ $item->paymentmethod }} | @endif{{ strtoupper($item->paymentstatus) }}</td>
	<td nowrap>{{ $item->cramount }}</td>
	<td nowrap>{{ $item->dramount }}</td>
	<td nowrap>@if($vendorid!=0 && $vendorid!='') {{ $balance }} @endif</td>
	<td nowrap>
	@if($item->servicetitle!='')
		AMOUNT DEDUCTED AGAINST {{ $item->servicetitle }} - TAXABLE AMOUNT {{$item->taxable}}<br>
	@endif
	{{ $item->paymentremark }}
	</td>
	<td nowrap>{{ $item->razorpay_order_id }}</td>
	<td nowrap>{{ $item->razorpay_payment_id }}</td>
	<td nowrap>{{ $item->receiptnumber }}
		<a href="{{ asset('storage/receipts/'.$item->receiptfile) }}" target="_blank" style="text-decoration:none;">
			<i class="fa fa-print"></i>
		</a> 	
	</td>
	<td nowrap class="center">
	@if($item->paymentfile!='NA' && $item->paymentfile!='')
        <a href="{{ asset('storage/'.$item->paymentfile) }}" target="_blank"><i class="fa fa-file"></i></a>		
	@endif	
	</td>
    <td nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		@if($item->razorpay_order_id=='' && $item->dramount==0)
		<a href="{{ route('edit.wallettransaction',Crypt::encrypt($item->receiptid)) }}" title="" class="myactionlink"><i class="fa fa-edit"></i></a>
		@endif
	@endif
	</td>	
	
</tr>
@endforeach
@if($i==1)
<tr>
    <td style="text-align:center;" colspan="13">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td style="text-align:right;" colspan="13">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
paginationLinks.forEach(link => {
	link.onclick = function(event) {
		event.preventDefault(); // Prevent default link behavior
		const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
		const url = '{{ route('wallettransaction.html') }}'; // URL generated by Laravel route
		loadData(page, url); // Call custom function with page number and URL
	};
});
</script>

