@php
$i=1
@endphp
@foreach ($data as $item)
<tr class="mytr" id="item-{{ $i }}">
    <td class="padding-10" style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td class="padding-10" nowrap>{{ $item->name }}</td>
	<td class="padding-10" nowrap>{{ $item->designation }}</td>
	<td class="padding-10" nowrap>{{ $item->department }}</td>
	<td class="padding-10" nowrap>{{ $item->mobilenumber }}</td>
	<td class="padding-10" nowrap>{{ $item->email }}</td>
    <td class="padding-10" nowrap style="text-align:center;">
	@if(in_array(2,Session::get('actions')))
		<a href="{{ route('edit.cmtmember',Crypt::encrypt($item->memberid)) }}" title=""><i class="fa fa-edit"></i></a></td>
	@endif
    <td class="padding-10" nowrap style="text-align:center;">
	@if(in_array(3,Session::get('actions')))
        <a title="" onclick="deleteItem('cmtmember','{{ Crypt::encrypt($item->memberid) }}',{{ $i }},'{{ __('messages.confirmation') }}','{{ __('messages.deleted') }}')" title=""><i class="fa fa-trash"></i>
        </a>
	@endif
    </td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td class="padding-10 center" colspan="8">
        <br>
        <i class="fa fa-warning blue nodata"></i><br>
        {!! __('messages.sorry') !!}
    </td>
</tr>
@else
<tr>
<td colspan="8" class="padding-10" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('cmtmember.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

