@php
$i=1
@endphp
@foreach ($data as $item)
@php
$baseprice	=	$item->remuneration;
$withtax	=	$item->remuneration+(($item->remuneration*$item->tax)/100);
$withadmin	=	$withtax+(($withtax*$item->admincharge)/100);
@endphp
<tr class="mytr" id="item-{{ $i }}">
    <td class="padding-10" style="width:30px; text-align:center;" nowrap>{{ $i++ }}</td>
	<td class="padding-10" nowrap>{{ ucwords(strtolower($item->sectorname)) }}</td>
	<td class="padding-10" nowrap>{{ ucwords(strtolower($item->consultantposition)) }}</td>
	<td class="padding-10" nowrap>{{ strtoupper($item->tiername)	 }}</td>
	<td class="padding-10" nowrap>{{ $item->remuneration }}</td>
    <td class="padding-10" nowrap>{{ number_format($withtax,'2','.','') }}</td>
	<td class="padding-10" nowrap>{{ number_format($withadmin,'2','.','') }}</td>
</tr>
@endforeach
@if($i==1)
<tr>
    <td colspan="7" class="padding-10 center">
        <br>
		@include('admin.body.actionmessage')
    </td>
</tr>
@else
<tr>
<td colspan="7" style="text-align:right;">
{{ $data->links('vendor.pagination.default') }}
</td>
</tr>
@endif

<script>
const paginationLinks = document.querySelectorAll('.pagination a');
        paginationLinks.forEach(link => {
            link.onclick = function(event) {
                event.preventDefault(); // Prevent default link behavior
                const page = this.getAttribute('href').split('page=')[1]; // Extract page number from URL
                const url = '{{ route('deptratelist.html') }}'; // URL generated by Laravel route
                loadData(page, url); // Call custom function with page number and URL
            };
        });
</script>

